---
- name: Install required packages
  package:
    name:
    - adduser
    - libfontconfig1
    - musl
    state: present

- name: Check if Grafana is installed
  command: dpkg-query -W grafana-enterprise
  register: grafana_package_check
  failed_when: grafana_package_check.rc > 1
  changed_when: grafana_package_check.rc == 1

- name: Download distributin file
  get_url:
    url: "{{ grafana_source_url }}"
    dest: /tmp
  register: source_file
  when: grafana_package_check.rc == 1

- name: Install Grafana package
  apt: deb="{{ source_file.dest }}"
  when: grafana_package_check.rc == 1

- name: Enable Grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Copy Grafana config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
  with_items:
    - { src: grafana.ini.j2, dest: /etc/grafana/grafana.ini }

- name: Restart Grafana service
  service:
    name: grafana-server  
    state: restarted