---
- name: Download zabbix repository install file
  get_url:
    url: "{{ repo_download_url }}"
    dest: /tmp
    force: true
  register: repo_file

- name: Install Zabbix repository
  apt:
    deb: "{{ repo_file.dest }}"

- name: Update apt cache if needed.
  apt:
    update_cache: yes

- name: Install required packages for Zabbix server
  apt:
    name: "{{ item }}"
    state: present
  with_items: 
  - postgresql
  - zabbix-server-pgsql
  - zabbix-frontend-php
  - php8.1-pgsql
  - zabbix-nginx-conf
  - zabbix-sql-scripts
  - zabbix-agent

- name: install acl for work with setfacl (need for postgresql Ansible module)
  apt:
    name: acl
    state: present

- name: Create zabbix user in postgresql
  community.postgresql.postgresql_user:
    name: "{{ zabbix_db_user_name }}"
    password: "{{ lookup('env', 'PG_ZABBIX_USER_PWD') }}"
    state: present
  become_user: postgres

- name: Create zabbix database in postgresql
  community.postgresql.postgresql_db:
    name: "{{ zabbix_db_name }}"
    owner: zabbix
  become_user: postgres

- name: Restore zabbix database schema
  shell: sudo zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

# - name: Reassign all object in database zabbix
#   postgresql_owner:
#     db: zabbix
#     new_owner: zabbix
#     reassign_owned_by: postgres
#   become_user: postgres

# - name: Extract zabbix schema database
#   command: gunzip -kf /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz

# - name: Restore database
#   community.postgresql.postgresql_db:
#     name: "{{ zabbix_db_name }}"
#     state: restore
#     target: /usr/share/zabbix-sql-scripts/postgresql/server.sql
#     owner: zabbix
#   become_user: postgres

# - name: GRANT ALL PRIVILEGES ON DATABASE zabbix TO zabbix user
#   community.postgresql.postgresql_privs:
#     db: zabbix
#     privs: ALL
#     type: database
#     role: zabbix
#   become_user: postgres

- name: Copy config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
  with_items:
  - { src: zabbix_server.conf.j2, dest: /etc/zabbix/zabbix_server.conf }  
  - { src: nginx.conf.j2, dest: /etc/zabbix/nginx.conf }  
  notify: Restart Zabbix

- name: Enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
  - zabbix-server
  - zabbix-agent
  - nginx
  - php8.1-fpm