---
- name: Download zabbix repository install file
  get_url:
    url: "{{ repo_download_url }}"
    dest: /tmp
    force: true
  register: repo_file

- name: Install Zabbix repository
  apt:
    deb: "{{ repo_file.dest }}"

- name: Update apt cache if needed.
  apt:
    update_cache: yes

- name: Install required packages for Zabbix server
  apt:
    name: "{{ item }}"
    state: present
  with_items: 
  - postgresql
  - zabbix-server-pgsql
  - zabbix-frontend-php
  - php8.1-pgsql
  - zabbix-nginx-conf
  - zabbix-sql-scripts
  - zabbix-agent

- name: install acl for work with setfacl (need for postgresql Ansible module)
  apt:
    name: acl
    state: present

- name: Create zabbix user in postgresql
  community.postgresql.postgresql_user:
    name: "{{ zabbix_db_user_name }}"
    password: "{{ lookup('env', 'PG_ZABBIX_USER_PWD') }}"
    state: present
  become_user: postgres

- name: Create zabbix database in postgresql
  community.postgresql.postgresql_db:
    name: "{{ zabbix_db_name }}"
    owner: zabbix
  become_user: postgres

- name: Restore database
  community.postgresql.postgresql_db:
    name: "{{ zabbix_db_name }}"
    state: restore
    target: /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz